version : '3.4'

networks:
  nw:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    hostname: mysql
    # Set sql_mode manually
    command: mysqld --sql_mode=""
    volumes:
      # - ./scripts/mysql:/root/scripts:ro
       - ./scripts/init.d:/docker-entrypoint-initdb.d:ro
       - ./mysql-storage:/var/lib/mysql # Persistent storage
    environment:
      # Default MYSQL-conf
      MYSQL_DATABASE: db
      MYSQL_USER: drew
      MYSQL_PASSWORD: drew
      MYSQL_ROOT_PASSWORD: XeoNu86JTznxMCQuGHrGutF3Csq5
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    cap_add: # Prevent mbind errors
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - nw
  
  earlyaccess.htb:
    build:
      context: .
      dockerfile: .docker/Dockerfile-webserver
    image: webserver
    container_name: webserver
    hostname: webserver
    environment:
      ADMIN_PW: gameover
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/src:/var/www/html
      - ./web/game:/var/www/earlyaccess.htb/game:ro
      - ./web/dev:/var/www/earlyaccess.htb/dev:ro
    depends_on:
      - mysql
      - api
    networks:
      - nw
    
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile-api
    container_name: api
    image: "api"
    restart: on-failure
    hostname: api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount to api to allow listing of images
      - ./api:/opt/api:ro # Source-code
    environment: 
      # Flask config - dev or prod
      FLASK_ENV: production # production || development
      DEBUG: "False" #"False" ||"True"
    networks:
      - nw
    
  admin-simulation:
    build:
      context: .
      dockerfile: .docker/Dockerfile-admin
    image: admin-simulation
    container_name: admin-simulation
    hostname: admin
    environment:
      ADMIN_PW: gameover
    volumes: 
      - ./admin_simulation:/root/admin_simulation:ro
    depends_on:
      - earlyaccess.htb
    networks:
      - nw

  # Auto-restarts unhealthy containers
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  game-server:
    build:
      context: .
      dockerfile: game-server/Dockerfile
    image: game-server
    container_name: game-server
    hostname: game-server
    volumes:
      - /opt/docker-entrypoint.d/:/docker-entrypoint.d
    #healthcheck:
    #  test: ["CMD", "curl --silent --fail localhost:9999 || exit 1"]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 2
    #  start_period: 10s
    #labels:
    #- "autoheal=true"

  npm:
    hostname: npm
    image: node:14
    container_name: npm
    volumes:
      - ./web/src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - nw