FROM php:7.4.1-apache

USER root

WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
        libpng-dev \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libonig-dev \
        zip \
        curl \
        unzip \
        cron \
        vim \
        python3 \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy VHost config
COPY .docker/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# Setup SSL-Cert
COPY scripts/gen_ssl.sh /opt/gen_ssl.sh
RUN bash /opt/gen_ssl.sh

# Setup composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Setup web directory
RUN chown -R www-data:www-data /var/www/ \
    && a2enmod rewrite

# Setup cron-job
RUN echo '* * * * * www-data cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1' >> /etc/crontab

# Wait time for mysql to be fully setup
ENV time=20

# Setup entrypoint
COPY scripts/entry.sh /root/entry.sh
ENTRYPOINT /root/entry.sh
