FROM ubuntu:latest

USER root

WORKDIR /root

RUN ln -s /dev/null /root/.bash_history

# Non interactive install
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-pip curl unzip wget cron util-linux \
    fonts-liberation libasound2 libatk-bridge2.0-0 \
    libnss3 lsb-release xdg-utils libxss1 libdbus-glib-1-2 \
    libcairo2 libcups2 libgbm1 libgtk-3-0 libpango-1.0-0  libxkbcommon-x11-0
    
# install chromedriver and google-chrome
RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod +x /usr/bin/chromedriver && \
    rm chromedriver_linux64.zip

RUN CHROME_SETUP=google-chrome.deb && \
    wget -q -O $CHROME_SETUP "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" && \
    dpkg -i $CHROME_SETUP && \
    apt-get install -y -f && \
    rm $CHROME_SETUP

RUN pip3 install selenium
RUN pip3 install python-decouple

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Exec format header
RUN echo '#!/bin/bash' > /root/entry.sh
# Start cron service
RUN echo 'echo "$(env | grep "ADMIN_PW=.*")" >> /etc/environment' >> /root/entry.sh
RUN echo 'service cron start' >> /root/entry.sh
# Keep container running
RUN echo 'tail -f /dev/null' >> /root/entry.sh
# Make entry script executable
RUN chmod +x /root/entry.sh

# Run admin simulation periodically (flock protects overlapping of cron)
RUN echo '* * * * * root /usr/bin/flock -w 0 /var/cron.lock python3 /root/admin_automation/admin.py "$ADMIN_PW" > /var/log/admin_automation.log 2>&1' >> /etc/crontab

# Run entry
ENTRYPOINT [ "/root/entry.sh" ]